выполнено задание по теме Создание API. Swagger-UI, Postman
EvgeniyMalygin/creationApi_DZ_3_2 pull request #1
Opened 2022-10-28 17:27 UTC by EvgeniyMalygin

2022-10-31 18:43 UTC, OlgaLugacheva requested changes

2022-10-31 18:43 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/service/FacultyService.java
> +        return facultyRepository.findById(id).get();
вместо get() лучше orElseThrow() и **свое исключение**

2022-10-31 18:43 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/service/StudentService.java
> +        return studentRepository.findById(id).get();
здесь тоже убираем get()

2022-10-31 18:43 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +        }
как только удалим get() из метода эта проверка станет не нужна

2022-10-31 18:43 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controller/StudentController.java
> +        if (student == null) {
как только удалим get() из метода эта проверка станет не нужна

2022-10-31 18:43 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +        if (foundFaculty == null) {
здесь проверка не нужна, просто потому что Spring Не даст вернуть null

2022-10-31 18:43 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controller/StudentController.java
> +        if (foundStudent == null) {
здесь проверка не нужна, просто потому что Spring Не даст вернуть null в save

2022-10-31 19:08 UTC, OlgaLugacheva requested changes

2022-10-31 19:08 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/exceptions/NotFountException.java
> +
@ResponseStatus(HttpStatus.NOT_FOUND)

2022-11-13 11:55 UTC, volalex commented on src/main/java/ru/hogwarts/school/scripts422.sql
> +CREATE TABLE person (
1. названия полей в sql принято писать в lower_snake_case
2. Нужно добавить настройку FOREIGN KEY для связи таблиц

Остальное - верно

2022-11-17 16:52 UTC, merged